# These are supported funding model platforms

github: flexiondotorg, lah7
patreon: ubuntu_mate
open_collective: # Replace with a single Open Collective username
ko_fi: ubuntumate
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: https://ubuntu-mate.org/donate
